os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"
  - "/^v.*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - BRANCH=${TRAVIS_BRANCH}
  - COMMIT=${TRAVIS_COMMIT::7}
  - TAG=${TRAVIS_TAG}
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: SX5WMC5BIhJx11oD8Xv6HuZD1IruAlpraSz59nlEItI51FRsmkm4offkIdsRRXOylDG+sCJA4GvOo68MJ6INpNtaZc/Srd5cwTSQqY+PYQ+C+/XK6mfCDisFZsQ4taYX3Vg8hGynJTcwxFIzdfkRsqPbjVUJynrvoQiEyPjQq7uMHaHwxC17l/F3ZjOw55e6BtyLKKekrzdfETwg38l8H6UH1SA1ftM6Xo69/1AyV8hI7HX6adbWAtTImKjbp8rWIpYv/XK2n/7emc9Ky3xCBjLgZlvaEk5zlFjL090YgoUQp5RR7U32yLmIi9dElMSGnYdJ/QOVVplEfRrTWizi4Y6+V4/NyTnY+dn/RFUEQFJSacw1odjyDN1LvlgnsC/fgRdNbAlhIfsmQnK7sDhGsLNdwTGJzBCNv2ac+c4Gqh0UBACTXR843KZ4EuTa2JIpo4pXb+s5Vg3yHWxjhuWroGugl5xCcu3H0Gs/uGK6w2SgOhllcBYkvNdbQjEeBt9O0zUgAg1/kNz3Fn7ht9k5l6yejk6FUSD7Awxqid26UbGOSSKAgnKvoykdaLnn/RopjJMo+Y5JvwPofl9hiY8XOw9hAY4d+7vSgKuregUZ/aeop73ybjRhh9xaAPWSE/Z/42xNHSqAHC0O2tfF7O77OaF4EdpqTXZATMBTVbWMSF4=
  - secure: gowfEbS59eVGHEesWQlVsuzEA0ZCoXifSwt2+JL6geFecsqX1uS+HQb4lsP77Sx0KhZvAlWd8DPuRLXveO7wTo98AxURU/cY/yqFqKFer1CLOXzv+z90K2zXob7C7l4kmL9jO9++NejjJgukzaF7pE51iLdehQZ4WtF61vYMK4xegrkOcjhgmjF5KKSZC349V9pTDsH8GRFfdvkjaJeV6Rro7F9XjRM6ZARgu2zKVoCYyWQvbmkbjQ53Ptt4F4qxu60i1sclyMk209GB34dmz2+WZP9jk+Bp23qQsv/gTJMnVdJvYGkI8soBcZBGbP7CvPpxOmEU+YFk/JxXPYSS+O34FTKsfiU6rqTl2yOT7picbxRRBNrPNhFhb4rEJSHA04eNRnAaJOaU+br0d0Sxnmv9kz3LNYCyWQe/XmpS0t6VzSIm5O2iIJLrOtgqedsDjd7e1rT/4Y7eqWbRknsjXCkGTTc1yJlnF5v+iIorVI/H5F2QaHd9DjPgCTD1OzEhr7tCF19VT0Vtgeru1H7Cc6KQMNGXm473vCedKHxKpg7DhHV9hdq+SJFLhsT0OuCAUiAkRxmafeEu12QeAhUh4OMxjzT37/KDJM9ONsIDfZUeILUflKX6l7O9lRxxQLuB9EF4CaJ7nDIJAUARfe3Lao+Y15wD/Hrbfx3zlTR+jzI=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE}:${BRANCH}-${COMMIT} .
script: skip
after_success:
- if [[ -z "${TAG}" ]]; then echo "This commit hasn't been tagged, will not be pushed
  to dockerhub"; exit 0; fi
- docker --version
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker tag ${IMAGE}:${BRANCH} ${DOCKERHUB}/${IMAGE}:${TAG}
- docker push ${DOCKERHUB}/${IMAGE}:${TAG}
- echo "${DOCKERHUB}/${IMAGE}:${TAG}"
notifications:
  email:
    on_success: never
    on_failure: never
