os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v[0-9].*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: LkGFm5C8Oexabhqx5YyYQ7GZ83Dnx6q0zggfFOwS3Ifu7lQZ0XHZE3vj8c/etJGbPrytp34H5xd+paTalEWdNWHvSGTG8OSaAScMbzI3cczoKtueDx2eohWrd6ND7HigPyLKmHrh58eXJmP8Ck3g970nlJmezM5Ms4DrUFUYNvzWSvsU5/ITUw40exb+tcy0MeoJsZ96FOtkcyserad+/wY/6vKPCUko1YkToXyMkx1LbvjwcViKmtv4BwNSIEN8CJBm+gurvNb9qj+TRS7eYEZmkQiVQCYCmqXTmUfHsyg7M6iteloUavkzSGLjacX1il4nJToI5wY4EO0B/XFVK3xaWkRCMEAyfqrhYa7D0DrlITGTOyyVjBqwTs1lYncLY++8I9TbhVO56tec1dZOLes9Kl5eA5brLFPGH9MQhnFCglSoYjcDtP1RzYd1sEM7GZXXlt66V/dDxUohSY6xA5MORvLhySKj/PQOxRnu8YtEsQyTS/vfb9QQ2kKOMH7Sv1A6fBfdTS3UjuQJih2Ue/W5503mzMBJvGPDNLsq8ll8X76Gm3zF4r+VVVKE3WDKh4dJwnBRfXJRjKBIMBQT/zo7reXvfX4TYJyBtTU6uZ2I7dN784ehM2M2fltS0OP80blexczbhhIk27wtBegwPO+ffO4rFFuqW3mqxtbf8o8=
  - secure: tYYiEnKxJL3MeQGGqP2ulVZwmQS4WRD20qzjQuthQ1+2SbKYnJ9RayQoiJL/qohdjPsldusLb1JQHg1VZ1jdx7EL4iuYeYU0y+f/h1KMuLag+wRObUHIvy2BIesdQWy3k3t1D8zdgXpJi+IrOimPWvuwyLZd+27uI3NkiYn73mIunWEjqjsmBauFEI9eNPef/b2P3KCBVRmyATz5v8PSb00Eu7s0Hnl9zzgxCLfmtmyOqmZGOv9SkhLk2YPmPoGVN9GNUFU95ly5LxewFdu0CdxiBOrXKh4gJo9yEKeuGBiUrTLTjSbdut9GA3gvdQqTEyTAN+S5gzUc0lrTG3PINALZIL9Ql06JmHPASY5Ymi3bUFkEObdVk04Q6oTUT5M5xhus83ZJ6QQgLcFgGVs37zqhSsJvTZMSI7n1gTcN+Wh0n9VeLpVYU8wnJUiwtO6r1vcktpBU+JxRCT1QaqLj5bXHVZgu8DK1U2DfowRzXDsSFRyZDh4P7C+HkSetM7fQI3vCNGEso7F0MNpUGiaBve8QXiiy1paguD0mX63i4nBdmtwtL4T4s2x6B7tVV9gSLggH++AqTKJ27H0KTarH6FqMkB1+YpHNpDN64mWrESKoS+2CSpHCB9ENqBwNd7evSMVI5g+0JWgtJpo/eYYSATFlIVddDT3ajkMWUxcTHSU=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE} .
script: skip
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- if [[ "${TRAVIS_BRANCH}" == *test* ]]; then docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER};
  docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}; echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}";
  else docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}; docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH};
  echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}"; fi
notifications:
  email:
    on_success: never
    on_failure: never
